apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - svc-monitor-payment-gateway.yaml
  - svc-monitor-event-consumer.yaml
  - grafana-instance.yaml
  - grafana-datasource-prometheus.yaml
  - grafana-dashboard-payment.yaml
