apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-event-consumer
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: payment-event-consumer
  namespaceSelector:
    matchNames:
      - payment-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
