apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: payment-gateway-secret-store
  namespace: default
spec:
  provider:
    fake:
      data:
        - key: "api_key"
          value: "sk_test_51Tgl0CRnzZxdec4KdjIzjw6DvWpPb5xV16uihy4xYH5GdPUsaIzCPWkE033U5V77pbROOEECSR8Lmae0o2RS9a6E00Pasm4fL6"
        - key: "webhook_secret"
          value: "whsec_b4dfb661b31f22b30f62c356731fe4efd26ab2f56c43583799d9e8ba7fa949d1"
        - key: "url"
          value: "postgres://pguser:pgpassword@postgres:5432/payments?sslmode=disable"
