apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: payment-kafka-brokers
  namespace: payment-system
  labels:
    strimzi.io/cluster: payment-kafka
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
