apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: payment-events
  namespace: payment-system
  labels:
    strimzi.io/cluster: payment-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
    cleanup.policy: delete
