apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics-config
  namespace: payment-system
  labels:
    app: strimzi
data:
  jmx-exporter-config.yaml: |
    rules:
      - pattern: kafka.server<type=(.+), name=(.+)><>Value
        name: kafka_server_$1_$2
      - pattern: kafka.network<type=(.+), name=(.+)><>Value
        name: kafka_network_$1_$2
      - pattern: kafka.log<type=(.+), name=(.+)><>Value
        name: kafka_log_$1_$2
      - pattern: kafka.controller<type=(.+), name=(.+)><>Value
        name: kafka_controller_$1_$2
