apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: payment-gateway-secret-store
  namespace: default
spec:
  provider:
    fake:
      data:
        - key: "api_key"
          value: "sk_test_REPLACE_ME"
        - key: "webhook_secret"
          value: "whsec_REPLACE_ME"
        - key: "url"
          value: "postgres://pguser:pgpassword@postgres:5432/payments?sslmode=disable"
